    # Step 9: Tải và cài đặt Grafana
    - name: Download Grafana
      ansible.builtin.get_url:
        url: "https://dl.grafana.com/oss/release/grafana_11.3.0_amd64.deb"
        dest: "/tmp/grafana_11.3.0_amd64.deb"
        mode: '0644'

    - name: Install Grafana
      ansible.builtin.apt:
        deb: "/tmp/grafana_11.3.0_amd64.deb"

    - name: Start and enable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true
