- hosts: all
  become: true
  tasks:
  
  - name: Update (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Update (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"