  - name: Download Node Exporter
    ansible.builtin.get_url:
      url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
      dest: "/tmp/node_exporter-1.8.2.linux-amd64.tar.gz"
      mode: '0644'

  - name: Extract Node Exporter
    ansible.builtin.unarchive:
      src: "/tmp/node_exporter-1.8.2.linux-amd64.tar.gz"
      dest: "/tmp"
      remote_src: yes

  - name: Move Node Exporter binary to /usr/local/bin
    ansible.builtin.command:
      cmd: "mv /tmp/node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/node_exporter"
    args:
      creates: "/usr/local/bin/node_exporter"

  - name: Set permissions on Node Exporter binary
    ansible.builtin.file:
      path: "/usr/local/bin/node_exporter"
      mode: '0755'

  - name: Ensure node_exporter user exists
    ansible.builtin.user:
      name: "node_exporter"
      shell: "/bin/false"
      system: yes
      state: present
      create_home: no  # Không tạo thư mục home cho người dùng system
    become: true       # Chạy lệnh với quyền root (nếu cần thiết)


  - name: Create systemd service file for Node Exporter
    ansible.builtin.template:
      src: "node_exporter.service.j2"
      dest: "/etc/systemd/system/node_exporter.service"
      mode: '0644'

  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start Node Exporter service
    ansible.builtin.systemd:
      name: node_exporter
      state: started
      enabled: true